insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (1,21,'Kohler Morar and Lockman',1949);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (2,14,'Gutkowski Dickens and Funk',1944);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (3,8,'Walsh Doyle and Marvin',1810);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (4,16,'Douglas',1832);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (5,12,'Predovic and Sons',1963);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (6,8,'Mueller and Sons',2001);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (7,12,'Breitenberg-Padberg',1826);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (8,13,'Hermiston-Kessler',1819);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (9,14,'Rempel Dare and King',2016);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (10,9,'Lakin Rolfson and Welch',1802);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (11,11,'Nader',1959);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (12,12,'Herman Rath and Erdman',1953);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (13,17,'Rohan-Trantow',1841);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (14,15,'Kuphal Kessler and Christiansen',1884);
insert into drustva (id, stevilo_clanov, ime, leto_ustanovitve) values (15,18,'Rath-Prohaska',1883);