insert into drustva (id, ime, leto_ustanovitve) values (1,'Kohler Morar and Lockman',1949);
insert into drustva (id, ime, leto_ustanovitve) values (2,'Gutkowski Dickens and Funk',1944);
insert into drustva (id, ime, leto_ustanovitve) values (3,'Walsh Doyle and Marvin',1810);
insert into drustva (id, ime, leto_ustanovitve) values (4,'Douglas',1832);
insert into drustva (id, ime, leto_ustanovitve) values (5,'Predovic and Sons',1963);
insert into drustva (id, ime, leto_ustanovitve) values (6,'Mueller and Sons',2001);
insert into drustva (id, ime, leto_ustanovitve) values (7,'Breitenberg-Padberg',1826);
insert into drustva (id, ime, leto_ustanovitve) values (8,'Hermiston-Kessler',1819);
insert into drustva (id, ime, leto_ustanovitve) values (9,'Rempel Dare and King',2016);
insert into drustva (id, ime, leto_ustanovitve) values (10,'Lakin Rolfson and Welch',1802);
insert into drustva (id, ime, leto_ustanovitve) values (11,'Nader',1959);
insert into drustva (id, ime, leto_ustanovitve) values (12,'Herman Rath and Erdman',1953);
insert into drustva (id, ime, leto_ustanovitve) values (13,'Rohan-Trantow',1841);
insert into drustva (id, ime, leto_ustanovitve) values (14,'Kuphal Kessler and Christiansen',1884);
insert into drustva (id, ime, leto_ustanovitve) values (15,'Rath-Prohaska',1883);