insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (-2000,'Mount Pulag',2926,'Cordillera','Filipini');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (569,'Matajur',1642,'Prealps','Slovenija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (663,'Mount Fuji',3776,'osamelec','Japonska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (905,'Mount Damavand',5610,'Alborz','Iran');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1275,'Canigou',2785,'Pyrenees','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1348,'Benediktenwand',1801,'Prealps','Nemcija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1358,'Rocciamelone',3538,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1387,'Pilatus',2128,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1492,'Mont Aiguille',2085,'Prealps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1500,'Llullaillaco',6739,'Andes','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1503,'Table Mountain',1086,'osamelec','Juzna Afrika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1519,'Popocatépetl',5426,'Sierra Nevada (Mex)','Mehika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1536,'Stockhorn',2190,'Prealps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1552,'Pic du Midi dOssau',2884,'Pyrenees','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1559,'Calanda',2805,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1573,'Corno Grande',2912,'Apennines','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1579,'Serles',2717,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1582,'Pichincha',4784,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1615,'Kežmarský štít',2558,'Carpathians','Slovaska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1642,'Mount Washington',1917,'Appalachians','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1654,'W. Karwendelspitze',2385,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1680,'Säntis',2502,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1707,'Piz Beverin',2998,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1726,'Monte Cavallo',2251,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1730,'Schesaplana',2965,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1738,'Corazón',4790,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1744,'Titlis',3238,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1750,'Hekla',1488,'Highlands of Iceland','Islandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1759,'Grintovec',2558,'Alps','Slovenija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1762,'Ankogel',3252,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1770,'Mont Buet',3096,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1771,'Ben Nevis',1334,'Grampian Range','Velika Britanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1775,'Lomnický štít',2634,'Carpathians','Slovaska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1778,'Triglav',2864,'Alps','Slovenija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1779,'Mont Vélan',3727,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1782,'Sulzfluh',2817,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1782,'Scopi',3190,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1784,'Dôme du Goűter',4304,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1784,'Dents du Midi',3257,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1786,'Mangart',2677,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1786,'Mont Blanc',4808,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1788,'Klyuchevskaya Sopka',4750,'Kamchatka','Rusija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1789,'Rheinwaldhorn',3402,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1792,'Oberalpstock',3328,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1792,'Vignemale',3298,'Pyrenees','Spanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1792,'Klein Matterhorn',3883,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1795,'Großes Wiesbachhorn',3564,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1799,'Kleinglockner',3770,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1800,'Großglockner',3797,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1800,'Watzmann',2713,'Alps','Nemcija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1800,'Mount Apo',2954,'Apo–Talomo','Filipini');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1802,'Monte Perdido',3355,'Pyrenees','Spanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1804,'Mount Katahdin',1608,'Appalachians','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1804,'Ortler',3905,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1808,'Grande Sassičre',3747,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1811,'Jungfrau',4158,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1813,'Breithorn',4164,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1819,'Torstein',2948,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1820,'Pikes Peak',4302,'Rocky Mountains','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1820,'Zumsteinspitze',4563,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1820,'Zugspitze',2962,'Alps','Nemcija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1821,'Schrankogel',3497,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1824,'Tödi',3614,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1827,'Mount Brown',2791,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1828,'Mont Pelvoux',3946,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1828,'Kitzsteinhorn',3203,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1828,'Pizzo Tambo',3279,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1829,'Mount Elbrus (East)',5621,'Caucasus','Rusija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1829,'Finsteraarhorn',4272,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1829,'Mount Ararat',5137,'osamelec','Turcija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1830,'Schalfkogel',3537,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1832,'Hoher Dachstein',2995,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1834,'Similaun',3606,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1834,'Gerlachovský štít',2655,'Carpathians','Slovaska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1835,'Piz Linard',3410,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1835,'Piz Palü',3898,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1836,'Fernerkogel',3294,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1836,'Habicht',3277,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1839,'Aiguilles d Arves',3513,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1839,'Mount Egmont',2518,'North Island volcanoes','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1840,'Rysy',2503,'Carpathians','Slovaska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1841,'Ras Dashen',4550,'Ethiopian Highlands','Etiopija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1841,'Glittertind',2465,'Scandinavian Mts','Norveska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1841,'Großvenediger',3666,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1842,'Aneto',3404,'Pyrenees','Spanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1842,'Lauteraarhorn',4042,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1842,'Fremont Peak',4189,'Rocky Mountains','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1843,'Großer Löffler',3376,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1844,'Wetterhorn',3692,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1845,'Weißkugel',3739,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1846,'Piz Kesch',3418,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1847,'Schrammacher',3410,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1847,'Bazardüzü',4466,'Caucasus','Azerbajdzan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1848,'Pico de Orizaba',5636,'Sierra Nevada (Mex)','Mehika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1848,'Wildspitze',3770,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1848,'Monte Rosa (Dunantspitze)',4632,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1850,'Galdhřpiggen',2469,'Scandinavian Mts','Norveska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1850,'Piz Bernina',4049,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1851,'Pico Duarte',3098,'Hispaniola','Dominikanska republika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1853,'Mount St. Helens',2950,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1854,'Mount Shasta',4322,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1854,'Königspitze',3859,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1854,'Hochgall',3436,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1854,'Mount Adams',3743,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1855,'Monte Rosa (Dufourspitze)',4634,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1855,'Weissmies',4017,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1857,'Mount Hood',3429,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1857,'Mönch',4107,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1857,'Pelmo',3168,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1858,'Eiger',3967,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1858,'Dom',4545,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1859,'Aletschhorn',4193,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1859,'Grand Combin',4314,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1859,'Bietschhorn',3934,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1859,'Grivola',3969,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1859,'Rimpfischhorn',4199,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1860,'Grande Casse',3855,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1860,'Gran Paradiso',4061,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1860,'Monte Civetta',3220,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1861,'Schreckhorn',4078,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1861,'Weisshorn',4506,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1861,'Monte Viso',3841,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1861,'Mont Pourri',3779,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1861,'Mount Cameroon',4070,'osamelec','Kamerun');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1862,'Dent Blanche',4357,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1862,'Zuckerhütl',3507,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1862,'Monte Disgrazia',3678,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1863,'Piz Zupň',3996,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1863,'Dent dHérens',4171,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1863,'Antelao',3264,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1864,'Barre des Écrins',4102,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1864,'Wannenhorn',3906,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1864,'Zinalrothorn',4221,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1864,'Adamello',3554,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1864,'Marmolada',3343,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1860,'Mount Tom',4163,'Sierra Nevada (U.S.)','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1865,'Piz Roseg',3937,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1865,'Aiguille Verte',4121,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1865,'Obergabelhorn',4063,'Alps','Svica');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1865,'Matterhorn',4478,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1865,'Piz Buin',3312,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1867,'Piz Badile',3308,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1868,'Grandes Jorasses',4208,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1868,'Kazbek',5047,'Caucasus','Gruzija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1868,'Mount Baker',3286,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1868,'Longs Peak',4345,'Rocky Mountains','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1869,'Langkofel',3181,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1869,'Große Zinne/ Cima Grande',2999,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1869,'Watzespitze',3533,'Alps','Avstrija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1870,'Ailefroide',3954,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1870,'Mount Rainier',4392,'Cascade Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1871,'Mount Lyell',3999,'Sierra Nevada (U.S.)','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1872,'Mount Ritter',4008,'Sierra Nevada (U.S.)','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1872,'Cotopaxi',5897,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1873,'Mount Whitney',4421,'Sierra Nevada (U.S.)','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1874,'Mount Elbrus (West)',5642,'Caucasus','Rusija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1874,'Blanca Peak',4372,'Rocky Mountains','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1874,'Mount Elbert',4404,'Rocky Mountains','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1875,'Half Dome',2693,'Sierra Nevada (U.S.)','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1876,'Store Skagastřlstind',2405,'Scandinavian Mts','Norveska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1877,'Meije',3983,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1877,'Mount Kerinci',3805,'Barisan Mountains','Poljska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1878,'Aiguille du Dru',3754,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1879,'Mount Ruapehu',2797,'Taupo Volcanic Zone','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1879,'Petit Dru',3733,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1880,'Chimborazo',6270,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1880,'Antisana',5704,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1880,'Cayambe',5790,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1880,'Mount Apo',2954,'Mindanao','Filipini');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1881,'Aiguille du Grépon',3482,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1882,'Dent du Géant',4013,'Alps','Francija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1883,'Kebnekaise',2111,'Scandinavian Mts','Svedska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1883,'Kabru E',7338,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1885,'Aiguille Blanche de Peuterey',4112,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1888,'Mount Kinabalu',4095,'Crocker Range','Malezija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1888,'Dykh-Tau',5205,'Caucasus','Rusija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1888,'Shkhara',5193,'Caucasus','Gruzija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1889,'Mount Victoria',4038,'Owen Stanley Range','Papuanska Nova Gvineja');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1889,'Kibo',5895,'Kilimanjaro','Tanzanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1889,'Iztaccihuatl',5230,'Sierra Nevada (Mex)','Mehika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1890,'Mount Sir Donald',3284,'Columbia Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1893,'Devils Tower',1558,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1894,'Mount Temple',3544,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1894,'Aoraki / Mount Cook',3764,'Southern Alps','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1895,'Mount Tasman',3497,'Southern Alps','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1895,'Delago Tower',2790,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1897,'Aconcagua',6959,'Andes','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1897,'Tupungato',6570,'Andes','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1897,'Mount Saint Elias',5489,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1898,'Grand Teton',4197,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1898,'Illimani',6438,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1898,'Jade Mountain',3952,'osamelec','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1899,'Campanile Basso',2883,'Alps','Italija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1899,'Batian',5199,'Mount Kenya','Kenija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1901,'Mount Assiniboine',3618,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1902,'Alam-Kuh',4848,'Alborz','Iran');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1902,'Mount Columbia',3747,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1902,'Mount Forbes',3612,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1902,'Mount Bryce',3507,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1903,'North Palisade',4343,'Sierra Nevada (U.S.)','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1903,'Ushba',4710,'Caucasus','Gruzija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1903,'Karisimbi',4507,'Virunga Mountains','Demokraticna Republika Kongo');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1904,'Mount Humphreys',4265,'Sierra Nevada (U.S.)','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1904,'Hozomeen Mountain',2460,'Cascade Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1904,'Mount Meru',4566,'osamelec','Tanzanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1906,'Mount Stanley',5109,'Rwenzori Mts','Uganda');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1907,'Trisul',7120,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1907,'Mount Olympus (US)',2432,'Olympic Mts','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1908,'Mount Erebus',3794,'Transantarctic Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1908,'Herđubreiđ',1682,'Highlands of Iceland','Islandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1908,'Maroon Bells',4317,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1908,'Huascaran N.',6655,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1909,'Mount Aspiring / Tititea',3033,'Southern Alps','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1910,'Denali N',5935,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1910,'Stetind',1394,'Scandinavian Mts','Norveska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1911,'Mitre Peak',1692,'osamelec','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1911,'Pauhunri',7128,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1911,'Coropuna',6425,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1911,'Wagagai',4321,'Mount Elgon','Uganda');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1912,'Mount Blackburn',4996,'Wrangell Mts','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1912,'Mount Sir Sandford',3519,'Columbia Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1912,'Mawenzi (Meyer Peak)',5148,'Kilimanjaro','Tanzanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1912,'Mount Bangeta',4121,'Saruwaged Range','Papuanska Nova Gvineja');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1913,'Puncak Trikora',4750,'Maoke Mountains','Poljska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1913,'Denali S',6168,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1913,'Mount Robson',3954,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1913,'Mount Olympus',2918,'osamelec','Grcija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1914,'Belukha',4506,'Altai Mountains','Kazahstan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1916,'Mount Louis',2682,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1916,'Crestone Peak',4357,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1916,'Bugaboo Spire',3204,'Columbia Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1919,'Huayna Potosí',6066,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1919,'Janq u Uma',6427,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1920,'Mount Cleveland',3194,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1920,'Lizard Head',3999,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1922,'Mount Moran',3842,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1922,'Gannett Peak',4209,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1923,'Jbel Toubkal',4167,'Atlas Mountains','Maroko');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1923,'Granite Peak',3904,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1925,'Mount Logan',5959,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1925,'Mount Alberta',3619,'Canadian Rockies','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1926,'Mount Russell',4296,'Sierra Nevada (U.S.)','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1927,'Mikeno',4437,'Virunga Mountains','Demokraticna Republika Kongo');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1928,'Illampu',6368,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1928,'Clyde Minaret',3740,'Sierra Nevada (U.S.)','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1928,'Lenin Peak',7134,'Pamir Mountains','Kirzigistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1930,'Jongsong Peak',7462,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1930,'Mount Bona',5005,'Saint Elias Mts','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1931,'Mount Fairweather',4671,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1931,'Kamet',7756,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1931,'Khan Tengri',7010,'Tian Shan','Kazahstan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1931,'Mount Tahat',2918,'Hoggar','Alzirija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1932,'Huascaran S.',6746,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1932,'Chopicalqui',6345,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1932,'Huandoy N.',6395,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1932,'Minya Konka',7556,'Daxue Shan','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1933,'Ismoil Somoni Peak',7495,'Pamirs','Tadzikistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1934,'Mercedario',6710,'Andes','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1934,'Mount Foraker',5304,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1934,'Sia Kangri',7422,'Karakoram','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1935,'Pico Bolívar',4978,'Andes','Venezuela');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1935,'Gunnbjřrn Fjeld',3694,'Watkins Range','Grenlandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1935,'Lingtren',6749,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Monarch Mountain',3555,'Coast Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Mount Waddington',4019,'Coast Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Siula Grande',6344,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Nanda Devi',7816,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Siniolchu',6888,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1936,'Mount Carstensz',4900,'Maoke Mountains','Indonezija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Ojos del Salado',6893,'Andes','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Jomolhari',7326,'Himalayas','Butan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Mount Lucania',5240,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Devils Tower',1637,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Mana',7272,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1937,'Kinnerly Peak',3032,'Rocky Mountains','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1938,'Mount Marcus Baker',4016,'Chugach Mts','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1938,'Mount Sanford',4949,'Wrangell Mts','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1938,'Mount Wilhelm',4509,'Bismarck Range','Papuanska Nova Gvineja');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1938,'Peak Pobeda',7439,'Tian Shan','Kirzigistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1938,'Pik Talgar',4979,'Tian Shan','Kazahstan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Pico Simón Bolívar',5700,'Sra Nevada de Sta Marta','Kolumbija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Pico Cristóbal Colón',5700,'Sra Nevada de Sta Marta','Kolumbija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Kirat Chuli',7365,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Dunagiri',7066,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Sajama',6550,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1939,'Shiprock',2188,'osamelec','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1941,'Kunturiri',5648,'Andes','Bolivija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1941,'Mount Hayes',4216,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1943,'Monte San Lorenzo',3706,'Patagonia','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1946,'Devils Thumb',2767,'Coast Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1947,'Lost Arrow Spire',2112,'Sierra Nevada (U.S.)','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1948,'Nevado Santa Cruz',6241,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1949,'Mount Vancouver',4812,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1950,'Annapurna',8091,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1950,'Tirich Mir',7708,'Hindu Kush','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1950,'Yerupajá',6617,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1951,'Mount Hubbard',4557,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'Fitz Roy',3405,'Patagonia','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'King Peak',5173,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'Mount Augusta',4289,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'Huantsán',6369,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'Salcantay',6271,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1952,'Monte San Valentin',4058,'Patagonia','Cile');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Mount Everest',8848,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Chamar',7187,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Nanga Parbat',8126,'Himalayas','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Mount Asgard',2015,'Baffin Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Ausangate',6372,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1953,'Nun',7135,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1954,'Mount Deborah',3761,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1954,'Mount Hunter',4442,'Alaska Range','Zdruzene drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1954,'K2',8611,'Karakorum','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1954,'Cho Oyu',8201,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1954,'Chomo Lonzo',7804,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1955,'Makalu',8481,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1955,'Kangchenjunga',8586,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1955,'Ganesh I',7422,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Lhotse',8516,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Manaslu',8156,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Muztagh Tower',7276,'Karakoram','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Gasherbrum II',8034,'Karakorum','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Chakrarahu',6108,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1956,'Muztagh Ata',7546,'Kunlun Mountains','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Pirámide',5885,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Machhapuchhare',6993,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Broad Peak',8047,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Skil Brum',7410,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Alpamayo',5947,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Jirishanca',6094,'Andes','Peru');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1957,'Cerro Paine Grande',2884,'Patagonian Andes','Cile');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1958,'Rakaposhi',7788,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1958,'Gasherbrum I',8080,'Karakorum','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1958,'Haramosh',7397,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1958,'Chogolisa II',7654,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1958,'Gasherbrum IV',7925,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1959,'Kanjut Sar',7760,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1959,'Saraghrar',7349,'Hindu Kush','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1959,'Puncak Mandala',4760,'Maoke Mountains','Indonezija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Dhaulagiri',8167,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Annapurna II',7937,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Himalchuli',7893,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Distaghil Sar',7885,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Masherbrum',7821,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Mount Proboscis',2610,'Mackenzie Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Noshaq',7492,'Hindu Kush','Afganistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1960,'Kuh-e Bandaka',6812,'Hindu Kush','Afganistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1961,'Ama Dablam',6856,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1961,'Nuptse',7861,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1961,'Castleton Tower',2029,'Utah','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1962,'Mount Fridtjof Nansen',4070,'Transantarctic Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1962,'Saltoro Kangri',7742,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1962,'Puncak Jaya',4884,'Maoke Mountains','Indonezija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1962,'Jannu',7710,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1963,'Central Tower of Paine',2460,'Patagonian Andes','Cile');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1963,'El Altar',5319,'Andes','Ekvador');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1963,'Mount Chamberlin',2749,'Brooks Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1963,'Khüiten Peak',4374,'Altai Mountains','Mongolija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'Lautaro',3623,'Patagonia','Cile');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'Gyachung Kang',7952,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'Shishapangma',8013,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'Mount Huntington',3731,'Alaska Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'The Mooses Tooth',3150,'Alaska Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1964,'Mount Paget',2935,'South Georgia','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1965,'Balls Pyramid',562,'Lord Howe Island','Nova Zelandija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1965,'Mount Kennedy',4238,'Saint Elias Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1965,'Mount Thor',1675,'Baffin Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1965,'Mount Nirvana',2773,'Mackenzie Mts','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1965,'Pico da Neblina',2994,'Guiana Highlands','Brazilija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1966,'Old Man of Hoy',137,'Orkney Islands','Velika Britanija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1966,'Mount Vinson',4897,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1967,'Mount Tyree',4852,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1967,'Barbeau Peak',2616,'Arctic Cordillera','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1970,'K6/Baltistan Peak',7282,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1970,'Ngadi Chuli',7871,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1971,'Dhaulagiri II',7751,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1971,'Malubiting',7458,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1971,'Khunyang Chhish',7852,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1973,'Saser Kangri I',7672,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'Cerro Torre',3128,'Patagonia','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'Nilkantha',6596,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'Shivling',6543,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'Changabang',6864,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'Shispare',7611,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1974,'K12',7428,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1975,'Chogolisa',7665,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1975,'Gasherbrum III',7946,'Karakoram','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1976,'Torre Egger',2685,'Patagonia','Argentina');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1976,'Batura Sar',7795,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1976,'Nameless Tower',6239,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1977,'The Ogre',7285,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1977,'Great Trango Tower',6286,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1978,'Langtang Lirung',7227,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1979,'Gauri Sankar',7134,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1979,'Thalay Sagar',6904,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1979,'Uli Biaho Tower',6109,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1979,'Latok',7145,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1980,'Mitre Peak',6010,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1980,'Chutine Peak',2910,'Coast Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1981,'The Spectre',2020,'Transantarctic Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1981,'Amne Machin',6282,'Kunlun Mountains','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1981,'Kongur Tagh',7649,'Kunlun Mountains','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1981,'Bogda Feng',5445,'Tian Shan','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1982,'Changtse',7543,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1984,'Yukshin Gardan Sar',7530,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1984,'Mamostong Kangri',7516,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1985,'Mount Hesperus',2996,'Alaska Range','Zdruzene Drzave Amerike');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1985,'Gurla Mandhata',7694,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1986,'Kula Kangri',7538,'Himalayas','Butan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1986,'Gyala Peri',7294,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1987,'Shanzidou',5596,'Mount Satseto','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1987,'Polar Sun Spire',1500,'Baffin Mountains','Kanada');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1987,'Labuche Kang',7367,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1988,'Mount Minto',4163,'Admiralty Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1988,'Rimo I',7385,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1988,'Chakragil',6760,'Kunlun Mountains','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1990,'Mount Sidley',4285,'Marie Byrd Land','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1990,'Xuelian Feng',6627,'Tian Shan','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1991,'Mount Kirkpatrick',4528,'Alexandra Range','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1992,'Menlungtse',7181,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1992,'Namcha Barwa',7782,'Himalayas','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1993,'The Crown',7295,'Karakoram','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1994,'Ulvetanna Peak',2930,'Queen Maud Land','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1994,'Passu Sar',7476,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1994,'Mount Epperly',4512,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1995,'Nyegyi Kansang',7047,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1996,'Peak 4111',4111,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1996,'Mount Foster',2105,'South Shetland','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1996,'Ultar Sar',7388,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1996,'Hkakabo Razi',5881,'Himalayas','Burma');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1997,'Rakekniven',2365,'Queen Maud Land','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (1999,'Gangkhar Puensum N',7535,'Himalayas','Butan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2001,'Meru C (Sharks Fin)',6310,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2002,'Sepu Kangri',6956,'Nyenchen Tanglha','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2002,'Num Ri',6677,'Himalayas','Nepal');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2005,'Tomort',4886,'Tian Shan','Kitajska');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2006,'Mount Rutford',4477,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2007,'Mount Anderson',4144,'Ellsworth Mts','Antarktika');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2009,'Changuch',6322,'Himalayas','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2011,'Saser Kangri II',7518,'Karakoram','Indija');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2013,'Kunyang Chhish East',7430,'Karakoram','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2013,'Gamlang Razi',5870,'Himalayas','Burma');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2014,'Gasherbrum V',7147,'Karakorum','Pakistan');
insert into oseba (prvi_pristop, ime, visina, gorovje, drzava) values (2018,'Lunag Ri',6907,'Himalayas','Nepal');