insert into gorovje (id, ime) values (1,'Cordillera');
insert into gorovje (id, ime) values (2,'Prealps');
insert into gorovje (id, ime) values (3,'osamelec');
insert into gorovje (id, ime) values (4,'Alborz');
insert into gorovje (id, ime) values (5,'Pyrenees');
insert into gorovje (id, ime) values (6,'Alps');
insert into gorovje (id, ime) values (7,'Andes');
insert into gorovje (id, ime) values (8,'Sierra Nevada (Mex)');
insert into gorovje (id, ime) values (9,'Apennines');
insert into gorovje (id, ime) values (10,'Carpathians');
insert into gorovje (id, ime) values (11,'Appalachians');
insert into gorovje (id, ime) values (12,'Highlands of Iceland');
insert into gorovje (id, ime) values (13,'Grampian Range');
insert into gorovje (id, ime) values (14,'Kamchatka');
insert into gorovje (id, ime) values (15,'Apo–Talomo');
insert into gorovje (id, ime) values (16,'Rocky Mountains');
insert into gorovje (id, ime) values (17,'Canadian Rockies');
insert into gorovje (id, ime) values (18,'Caucasus');
insert into gorovje (id, ime) values (19,'North Island volcanoes');
insert into gorovje (id, ime) values (20,'Ethiopian Highlands');
insert into gorovje (id, ime) values (21,'Scandinavian Mts');
insert into gorovje (id, ime) values (22,'Hispaniola');
insert into gorovje (id, ime) values (23,'Cascade Range');
insert into gorovje (id, ime) values (24,'Sierra Nevada (U.S.)');
insert into gorovje (id, ime) values (25,'Barisan Mountains');
insert into gorovje (id, ime) values (26,'Taupo Volcanic Zone');
insert into gorovje (id, ime) values (27,'Mindanao');
insert into gorovje (id, ime) values (28,'Himalayas');
insert into gorovje (id, ime) values (29,'Crocker Range');
insert into gorovje (id, ime) values (30,'Owen Stanley Range');
insert into gorovje (id, ime) values (31,'Kilimanjaro');
insert into gorovje (id, ime) values (32,'Columbia Mts');
insert into gorovje (id, ime) values (33,'Southern Alps');
insert into gorovje (id, ime) values (34,'Saint Elias Mts');
insert into gorovje (id, ime) values (35,'Mount Kenya');
insert into gorovje (id, ime) values (36,'Virunga Mountains');
insert into gorovje (id, ime) values (37,'Rwenzori Mts');
insert into gorovje (id, ime) values (38,'Olympic Mts');
insert into gorovje (id, ime) values (39,'Transantarctic Mts');
insert into gorovje (id, ime) values (40,'Alaska Range');
insert into gorovje (id, ime) values (41,'Mount Elgon');
insert into gorovje (id, ime) values (42,'Wrangell Mts');
insert into gorovje (id, ime) values (43,'Saruwaged Range');
insert into gorovje (id, ime) values (44,'Maoke Mountains');
insert into gorovje (id, ime) values (45,'Altai Mountains');
insert into gorovje (id, ime) values (46,'Atlas Mountains');
insert into gorovje (id, ime) values (47,'Pamir Mountains');
insert into gorovje (id, ime) values (48,'Tian Shan');
insert into gorovje (id, ime) values (49,'Hoggar');
insert into gorovje (id, ime) values (50,'Daxue Shan');
insert into gorovje (id, ime) values (51,'Pamirs');
insert into gorovje (id, ime) values (52,'Karakoram');
insert into gorovje (id, ime) values (53,'Watkins Range');
insert into gorovje (id, ime) values (54,'Coast Mountains');
insert into gorovje (id, ime) values (55,'Chugach Mts');
insert into gorovje (id, ime) values (56,'Bismarck Range');
insert into gorovje (id, ime) values (57,'Sra Nevada de Sta Marta');
insert into gorovje (id, ime) values (58,'Patagonia');
insert into gorovje (id, ime) values (59,'Hindu Kush');
insert into gorovje (id, ime) values (60,'Baffin Mountains');
insert into gorovje (id, ime) values (61,'Karakorum');
insert into gorovje (id, ime) values (62,'Kunlun Mountains');
insert into gorovje (id, ime) values (63,'Patagonian Andes');
insert into gorovje (id, ime) values (64,'Mackenzie Mts');
insert into gorovje (id, ime) values (65,'Utah');
insert into gorovje (id, ime) values (66,'Brooks Range');
insert into gorovje (id, ime) values (67,'South Georgia');
insert into gorovje (id, ime) values (68,'Lord Howe Island');
insert into gorovje (id, ime) values (69,'Guiana Highlands');
insert into gorovje (id, ime) values (70,'Orkney Islands');
insert into gorovje (id, ime) values (71,'Ellsworth Mts');
insert into gorovje (id, ime) values (72,'Arctic Cordillera');
insert into gorovje (id, ime) values (73,'Mount Satseto');
insert into gorovje (id, ime) values (74,'Admiralty Mts');
insert into gorovje (id, ime) values (75,'Marie Byrd Land');
insert into gorovje (id, ime) values (76,'Alexandra Range');
insert into gorovje (id, ime) values (77,'Queen Maud Land');
insert into gorovje (id, ime) values (78,'South Shetland');
insert into gorovje (id, ime) values (79,'Nyenchen Tanglha');
