insert into gorovje (id, ime, priimek, spol, starost) values ('Cordillera');
insert into gorovje (id, ime, priimek, spol, starost) values ('Prealps');
insert into gorovje (id, ime, priimek, spol, starost) values ('osamelec');
insert into gorovje (id, ime, priimek, spol, starost) values ('Alborz');
insert into gorovje (id, ime, priimek, spol, starost) values ('Pyrenees');
insert into gorovje (id, ime, priimek, spol, starost) values ('Alps');
insert into gorovje (id, ime, priimek, spol, starost) values ('Andes');
insert into gorovje (id, ime, priimek, spol, starost) values ('Sierra Nevada (Mex)');
insert into gorovje (id, ime, priimek, spol, starost) values ('Apennines');
insert into gorovje (id, ime, priimek, spol, starost) values ('Carpathians');
insert into gorovje (id, ime, priimek, spol, starost) values ('Appalachians');
insert into gorovje (id, ime, priimek, spol, starost) values ('Highlands of Iceland');
insert into gorovje (id, ime, priimek, spol, starost) values ('Grampian Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Kamchatka');
insert into gorovje (id, ime, priimek, spol, starost) values ('Apo-Talomo');
insert into gorovje (id, ime, priimek, spol, starost) values ('Rocky Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Canadian Rockies');
insert into gorovje (id, ime, priimek, spol, starost) values ('Caucasus');
insert into gorovje (id, ime, priimek, spol, starost) values ('North Island volcanoes');
insert into gorovje (id, ime, priimek, spol, starost) values ('Ethiopian Highlands');
insert into gorovje (id, ime, priimek, spol, starost) values ('Scandinavian Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Hispaniola');
insert into gorovje (id, ime, priimek, spol, starost) values ('Cascade Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Sierra Nevada (U.S.)');
insert into gorovje (id, ime, priimek, spol, starost) values ('Barisan Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Taupo Volcanic Zone');
insert into gorovje (id, ime, priimek, spol, starost) values ('Mindanao');
insert into gorovje (id, ime, priimek, spol, starost) values ('Himalayas');
insert into gorovje (id, ime, priimek, spol, starost) values ('Crocker Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Owen Stanley Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Kilimanjaro');
insert into gorovje (id, ime, priimek, spol, starost) values ('Columbia Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Southern Alps');
insert into gorovje (id, ime, priimek, spol, starost) values ('Saint Elias Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Mount Kenya');
insert into gorovje (id, ime, priimek, spol, starost) values ('Virunga Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Rwenzori Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Olympic Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Transantarctic Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Alaska Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Mount Elgon');
insert into gorovje (id, ime, priimek, spol, starost) values ('Wrangell Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Saruwaged Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Maoke Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Altai Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Atlas Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Pamir Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Tian Shan');
insert into gorovje (id, ime, priimek, spol, starost) values ('Hoggar');
insert into gorovje (id, ime, priimek, spol, starost) values ('Daxue Shan');
insert into gorovje (id, ime, priimek, spol, starost) values ('Pamirs');
insert into gorovje (id, ime, priimek, spol, starost) values ('Karakoram');
insert into gorovje (id, ime, priimek, spol, starost) values ('Watkins Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Coast Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Chugach Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Bismarck Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Sra Nevada de Sta Marta');
insert into gorovje (id, ime, priimek, spol, starost) values ('Patagonia');
insert into gorovje (id, ime, priimek, spol, starost) values ('Hindu Kush');
insert into gorovje (id, ime, priimek, spol, starost) values ('Baffin Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Karakorum');
insert into gorovje (id, ime, priimek, spol, starost) values ('Kunlun Mountains');
insert into gorovje (id, ime, priimek, spol, starost) values ('Patagonian Andes');
insert into gorovje (id, ime, priimek, spol, starost) values ('Mackenzie Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Utah');
insert into gorovje (id, ime, priimek, spol, starost) values ('Brooks Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('South Georgia');
insert into gorovje (id, ime, priimek, spol, starost) values ('Lord Howe Island');
insert into gorovje (id, ime, priimek, spol, starost) values ('Guiana Highlands');
insert into gorovje (id, ime, priimek, spol, starost) values ('Orkney Islands');
insert into gorovje (id, ime, priimek, spol, starost) values ('Ellsworth Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Arctic Cordillera');
insert into gorovje (id, ime, priimek, spol, starost) values ('Mount Satseto');
insert into gorovje (id, ime, priimek, spol, starost) values ('Admiralty Mts');
insert into gorovje (id, ime, priimek, spol, starost) values ('Marie Byrd Land');
insert into gorovje (id, ime, priimek, spol, starost) values ('Alexandra Range');
insert into gorovje (id, ime, priimek, spol, starost) values ('Queen Maud Land');
insert into gorovje (id, ime, priimek, spol, starost) values ('South Shetland');
insert into gorovje (id, ime, priimek, spol, starost) values ('Nyenchen Tanglha');