insert into oseba (id, ime, priimek, spol, starost, drustvo) values (1,'Ferne',"Tyas",'Female',42,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (2,'Doloritas',"Higgen",'Female',15,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (3,'Alfredo',"Ballay",'Male',44,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (4,'Forster',"Laminman",'Male',52,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (5,'Wiatt',"McHarry",'Male',28,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (6,'Tammie',"McPeeters",'Female',52,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (7,'Christin',"Jandourek",'Female',87,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (8,'Eduardo',"Jakab",'Male',43,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (9,'Lovell',"Abotson",'Male',82,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (10,'Juanita',"Archbutt",'Female',62,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (11,'Luther',"Scottesmoor",'Male',60,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (12,'Aldus',"Derks",'Male',15,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (13,'Cordelia',"Galsworthy",'Female',29,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (14,'Stafani',"Wheildon",'Female',79,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (15,'York',"Schrinel",'Male',33,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (16,'Filippo',"Vedntyev",'Male',27,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (17,'Odo',"Nodin",'Male',91,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (18,'Joanie',"Beminster",'Female',66,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (19,'Iosep',"Aviss",'Male',26,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (20,'Renado',"Mc Caghan",'Male',31,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (21,'Sherill',"Innes",'Female',93,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (22,'Serge',"Broxis",'Male',95,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (23,'Ashlee',"Dot",'Female',35,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (24,'Archibald',"Daughtery",'Male',44,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (25,'Lilli',"Winterton",'Female',31,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (26,'Sella',"Ilymanov",'Female',71,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (27,'Madalena',"Fellnee",'Female',68,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (28,'Bartel',"Sidwick",'Male',87,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (29,'Danielle',"Mordie",'Female',50,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (30,'Joe',"Sans",'Male',79,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (31,'Felix',"Maceur",'Male',68,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (32,'Garald',"Gameson",'Male',85,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (33,'Turner',"Gauchier",'Male',34,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (34,'Eva',"Tillman",'Female',74,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (35,'Evania',"Fettes",'Female',27,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (36,'Delila',"Grasner",'Female',77,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (37,'Bethanne',"Cattenach",'Female',70,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (38,'Gale',"Pleasants",'Female',23,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (39,'Lianne',"Parrett",'Female',29,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (40,'Marieann',"Brun",'Female',78,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (41,'Ewart',"Cawkwell",'Male',53,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (42,'Dmitri',"Brierly",'Male',49,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (43,'Trumaine',"O'Hanlon",'Male',70,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (44,'Dieter',"Geraudel",'Male',63,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (45,'Gelya',"Balnave",'Female',40,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (46,'Rice',"Kuschke",'Male',79,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (47,'Cleve',"Stroder",'Male',31,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (48,'Correna',"Vossgen",'Female',33,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (49,'Cazzie',"Hedley",'Male',46,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (50,'Haleigh',"Gyppes",'Female',69,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (51,'Thorndike',"Duddle",'Male',15,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (52,'Bronny',"Bindley",'Male',24,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (53,'Angy',"Iliffe",'Female',40,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (54,'Clarabelle',"Wedderburn",'Female',31,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (55,'Marnia',"Sugar",'Female',45,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (56,'Rance',"Riddett",'Male',32,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (57,'Shelagh',"De Bernardis",'Female',74,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (58,'Anitra',"Tune",'Female',45,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (59,'Ina',"Pedden",'Female',44,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (60,'Duffie',"Bilbey",'Male',86,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (61,'Lalo',"Kennett",'Male',25,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (62,'Pat',"Walklot",'Female',22,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (63,'Tremayne',"Wing",'Male',29,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (64,'Benjamen',"Balharrie",'Male',46,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (65,'Charmion',"Presidey",'Female',69,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (66,'Zachary',"Letty",'Male',43,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (67,'Alvan',"Glyne",'Male',15,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (68,'Yoshiko',"Tumber",'Female',90,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (69,'Archibaldo',"Furlonge",'Male',29,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (70,'Gal',"Recher",'Male',15,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (71,'Brittney',"Saunier",'Female',64,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (72,'Clark',"Gillino",'Male',65,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (73,'Matti',"Robet",'Female',22,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (74,'Remus',"Huntly",'Male',62,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (75,'Meaghan',"Knuckles",'Female',70,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (76,'Cyndy',"Kinworthy",'Female',15,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (77,'Willi',"Dzeniskevich",'Male',71,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (78,'Adlai',"Ast",'Male',17,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (79,'Ambrosius',"Fidock",'Male',80,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (80,'Karel',"Garrit",'Male',95,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (81,'Fancy',"Manuaud",'Female',88,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (82,'Agatha',"MacIlriach",'Female',74,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (83,'Pammie',"Kingcote",'Female',66,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (84,'Broddy',"Marrows",'Male',58,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (85,'Chrissie',"Ainsbury",'Female',40,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (86,'Boniface',"Livezley",'Male',68,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (87,'Othelia',"Lambrechts",'Female',18,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (88,'Claiborne',"Longmaid",'Male',31,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (89,'Monica',"Julyan",'Female',25,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (90,'Giustino',"Rathbone",'Male',35,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (91,'Hernando',"Biner",'Male',75,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (92,'Brinna',"Morewood",'Female',15,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (93,'Mariel',"Domenichini",'Female',78,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (94,'Wolfie',"Fishburn",'Male',89,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (95,'Gregorio',"Gillow",'Male',60,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (96,'Lizette',"Bathersby",'Female',56,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (97,'Nathanil',"Chastagnier",'Male',72,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (98,'Xenia',"Braine",'Female',19,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (99,'Yettie',"Evanson",'Female',28,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (100,'Jemie',"Chidwick",'Female',70,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (101,'Aleda',"Shipston",'Female',88,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (102,'Lorant',"Craythorn",'Male',45,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (103,'Noah',"Jeayes",'Male',23,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (104,'Danella',"Willshear",'Female',31,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (105,'Abbie',"Terrett",'Male',28,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (106,'Templeton',"Cathesyed",'Male',62,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (107,'Elenore',"Dickens",'Female',61,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (108,'Cosetta',"Jerman",'Female',94,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (109,'Aloin',"Bussell",'Male',20,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (110,'August',"Hinckesman",'Male',71,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (111,'Ruprecht',"Dyers",'Male',71,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (112,'Rosemary',"Berriball",'Female',27,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (113,'Huberto',"Shewsmith",'Male',62,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (114,'Florence',"Nosworthy",'Female',75,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (115,'Glennis',"Goschalk",'Female',25,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (116,'Brynna',"Tabour",'Female',48,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (117,'Quintin',"Worner",'Male',60,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (118,'Ashleigh',"Bramford",'Female',42,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (119,'Ivan',"Bloxsum",'Male',24,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (120,'Torin',"Pachmann",'Male',45,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (121,'Alice',"Kinner",'Female',22,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (122,'Sherill',"Tregea",'Female',17,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (123,'Augustine',"Kulas",'Male',17,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (124,'Herculie',"Wornham",'Male',92,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (125,'Augustine',"MacAloren",'Male',62,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (126,'Correna',"Rushsorth",'Female',53,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (127,'Win',"Coulthurst",'Male',51,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (128,'Westley',"McAvin",'Male',48,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (129,'Benedicto',"Pengilly",'Male',65,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (130,'Felicle',"Milnes",'Female',63,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (131,'Kristopher',"Doerren",'Male',59,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (132,'Dottie',"Sayburn",'Female',80,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (133,'Nydia',"Haycock",'Female',45,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (134,'Dev',"Chesnut",'Male',48,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (135,'Marshall',"Cuberley",'Male',82,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (136,'Inge',"Dobbing",'Female',88,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (137,'Jacklyn',"Franzen",'Female',74,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (138,'Amalita',"Rangeley",'Female',67,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (139,'Patin',"Coldbreath",'Male',46,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (140,'Erwin',"Assad",'Male',46,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (141,'Violetta',"Strelitz",'Female',76,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (142,'Ethe',"Rollingson",'Male',74,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (143,'Katharina',"Adrain",'Female',50,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (144,'Thea',"Fairnington",'Female',66,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (145,'Carmelina',"Cunnington",'Female',89,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (146,'Lilli',"Corringham",'Female',53,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (147,'Shell',"Tizzard",'Female',80,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (148,'Caprice',"Laity",'Female',22,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (149,'Shanon',"Smallthwaite",'Female',56,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (150,'Shell',"Jelley",'Female',16,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (151,'Danny',"Klezmski",'Female',29,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (152,'Lalo',"Le Maitre",'Male',65,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (153,'Sarette',"Bresman",'Female',52,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (154,'Nanni',"Ricker",'Female',33,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (155,'Moe',"Picot",'Male',89,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (156,'Pacorro',"Garie",'Male',53,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (157,'Babb',"McKyrrelly",'Female',77,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (158,'Anne-corinne',"Rozier",'Female',70,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (159,'Tomaso',"Songest",'Male',40,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (160,'Sherilyn',"Watting",'Female',15,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (161,'Mort',"Odlin",'Male',15,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (162,'Veronica',"Spivie",'Female',87,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (163,'Allyce',"Haselden",'Female',19,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (164,'Tristan',"Crosscombe",'Male',59,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (165,'Hobard',"Clixby",'Male',63,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (166,'Jammal',"Drakes",'Male',20,'Kuphal, Kessler and Christiansen');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (167,'Annmarie',"Bremmell",'Female',21,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (168,'Cleve',"Scone",'Male',33,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (169,'Hobie',"Otto",'Male',43,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (170,'Dex',"Shayler",'Male',60,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (171,'Zita',"Taggart",'Female',44,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (172,'Jozef',"Gierardi",'Male',29,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (173,'Rana',"Leadbeater",'Female',70,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (174,'Garrard',"Pilling",'Male',53,'Rempel, Dare and King');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (175,'Skylar',"Lade",'Male',64,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (176,'Hewitt',"Nezey",'Male',94,'Predovic and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (177,'Sargent',"Dmych",'Male',15,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (178,'Julianne',"Downe",'Female',63,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (179,'Cassaundra',"Olander",'Female',69,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (180,'Trudie',"Snowball",'Female',40,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (181,'Julissa',"Wetherald",'Female',80,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (182,'Robbin',"Burcher",'Female',53,'Gutkowski, Dickens and Funk');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (183,'Remus',"Woloschin",'Male',44,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (184,'Ginger',"Turgoose",'Male',71,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (185,'Ivonne',"Grumley",'Female',51,'Mueller and Sons');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (186,'Alvan',"Beyne",'Male',48,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (187,'Meaghan',"Bentham3",'Female',28,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (188,'Clementia',"Wann",'Female',53,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (189,'Kennan',"Joskowitz",'Male',17,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (190,'Terencio',"Sieghard",'Male',21,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (191,'Bartolemo',"Bambery",'Male',94,'Hermiston-Kessler');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (192,'Gallagher',"Linden",'Male',48,'Breitenberg-Padberg');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (193,'Ricki',"Shoutt",'Female',17,'Kohler, Morar and Lockman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (194,'Jenna',"Giacobazzi",'Female',85,'Nader');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (195,'Nicola',"Manilow",'Female',27,'Rath-Prohaska');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (196,'Augy',"Everit",'Male',62,'Douglas');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (197,'Garreth',"Carberry",'Male',71,'Lakin, Rolfson and Welch');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (198,'Matthaeus',"Duchan",'Male',54,'Walsh, Doyle and Marvin');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (199,'Madeline',"Croizier",'Female',15,'Herman, Rath and Erdman');
insert into oseba (id, ime, priimek, spol, starost, drustvo) values (200,'Tarrah',"Andretti",'Female',77,'Rohan-Trantow');
insert into oseba (id, ime, priimek, spol, starost, drustvo, uporabnik, geslo, polozaj) values (10000000000,'Kekec',"Kekec",'Male',14,'Rohan-Trantow', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 2);